version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fitness_app_postgres
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - fitness_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fitness_app_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fitness-app.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - fitness_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  fitness_network:
    driver: bridge
